apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bazitadebiyicometproject.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "bazitadebiyicometproject.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "bazitadebiyicometproject.name" . }}
    spec:
      containers:
      - name: {{ include "bazitadebiyicometproject.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env:
        - name: ENV_VAR
          value: {{ .Values.env.ENV_VAR | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.path }}
            port: {{ .Values.livenessProbe.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: {{ .Values.readinessProbe.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
