replicaCount: 2

image:
  repository: 690893780650.dkr.ecr.us-east-2.amazonaws.com/comet-ecr:b87efe1377a230e9f23475f6e38fdad8c14817a7
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

env:
  ENV_VAR: "prod"

livenessProbe:
  enabled: true
  path: /healthz
  port: 5000

readinessProbe:
  enabled: true
  path: /healthz
  port: 5000
