name: Terraform Plan on PR

on:
  pull_request:
    branches:
      - main
env:
  AWS_REGION: us-east-2
  
permissions:
      id-token: write
      contents: read
      pull-requests: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color -out=tfplan
          terraform show -no-color tfplan > plan.txt

      - name: Post Plan to PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: plan.txt
