name: Terraform Plan on PR

on:
  pull_request:
    branches:
      - main

permissions:
      id-token: write
      contents: read
      pull-requests: write

jobs:
  terraform-plan:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get OIDC Token
        id: oidc
        run: |
          echo "Requesting OIDC token from GitHub..."
          export REQUEST_URL="${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com"
          export ID_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$REQUEST_URL" | jq -r .value)
          if [ -z "$ID_TOKEN" ]; then
            echo "OIDC token is empty. Check that 'id-token: write' is set at the top-level permissions block."
            exit 1
          fi
          echo "::add-mask::$ID_TOKEN"
          echo "id_token=$ID_TOKEN" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::690893780650:role/gh_depolyer #to be imported to terraform
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color | tee plan.txt

      - name: Post Plan to PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: plan.txt